# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roupa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tamanho', models.CharField(max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cor', models.CharField(max_length=25)),
                ('tipo', models.CharField(max_length=15)),
                ('descricao', models.TextField()),
                ('situacao', models.CharField(max_length=50)),
            ],
        ),
    ]
